# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import llmserver_pb2 as llmserver__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in llmserver_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LLMServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/proto.LLMServer/Ping',
                request_serializer=llmserver__pb2.PingRequest.SerializeToString,
                response_deserializer=llmserver__pb2.PingResponse.FromString,
                _registered_method=True)
        self.LoadModel = channel.unary_stream(
                '/proto.LLMServer/LoadModel',
                request_serializer=llmserver__pb2.LoadModelRequest.SerializeToString,
                response_deserializer=llmserver__pb2.LoadModelResponse.FromString,
                _registered_method=True)
        self.Predict = channel.unary_stream(
                '/proto.LLMServer/Predict',
                request_serializer=llmserver__pb2.PredictRequest.SerializeToString,
                response_deserializer=llmserver__pb2.PredictResponse.FromString,
                _registered_method=True)


class LLMServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Predict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LLMServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=llmserver__pb2.PingRequest.FromString,
                    response_serializer=llmserver__pb2.PingResponse.SerializeToString,
            ),
            'LoadModel': grpc.unary_stream_rpc_method_handler(
                    servicer.LoadModel,
                    request_deserializer=llmserver__pb2.LoadModelRequest.FromString,
                    response_serializer=llmserver__pb2.LoadModelResponse.SerializeToString,
            ),
            'Predict': grpc.unary_stream_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=llmserver__pb2.PredictRequest.FromString,
                    response_serializer=llmserver__pb2.PredictResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.LLMServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.LLMServer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LLMServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.LLMServer/Ping',
            llmserver__pb2.PingRequest.SerializeToString,
            llmserver__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/proto.LLMServer/LoadModel',
            llmserver__pb2.LoadModelRequest.SerializeToString,
            llmserver__pb2.LoadModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/proto.LLMServer/Predict',
            llmserver__pb2.PredictRequest.SerializeToString,
            llmserver__pb2.PredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
